import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import crypto from 'node:crypto';
const arg=(n,d)=>{const i=process.argv.indexOf(n);return i>=0?process.argv[i+1]:d},target=path.resolve(arg('--target','/tmp/auto-upstream')),out=path.resolve(arg('--out','arena')),ev=path.join(out,'evidence');fs.mkdirSync(ev,{recursive:true});
const scripts={p119:'p119_continuous_evolution.mjs',p121:'p121_independent_learning_discovery.mjs',p129:'p129_recursive_meta_evolution.mjs',p130:'p130_meta_governance.mjs',p134:'p134_unstructured_discovery.mjs',p137b:'p137b_ontology_generation.mjs',p138:'p138_open_creation_challenge.mjs',p140:'p140_true_ontogenesis.mjs'};const runs={},src={};for(const[id,file]of Object.entries(scripts)){const full=path.join(target,'scripts/pipeline',file);src[id]=fs.readFileSync(full,'utf8');const r=spawnSync('node',[full],{cwd:target,encoding:'utf8',timeout:120000});runs[id]={exit:r.status,stdout:r.stdout,stderr:r.stderr};fs.writeFileSync(path.join(ev,`auto_v2_${id}.stdout.log`),r.stdout);fs.writeFileSync(path.join(ev,`auto_v2_${id}.stderr.log`),r.stderr);}
const checks={
 p129_pre_authored:/const mechanismV02\s*=/.test(src.p129)&&/const expected\s*=/.test(src.p129),
 p130_circular:/const expected\s*=\s*inputs\.map[\s\S]*rotordown/.test(src.p130),
 p130_stub:/fn\$applyRotordown[\s\S]*return x/.test(src.p130),
 p134_source_and_oracle_same_constant:(src.p134.match(/2654435761/g)||[]).length>=4,
 p134_circular_future:/predicted = oracleLaw\(f\)[\s\S]*actual = \(\(f \+ 1\) \* 2654435761\)/.test(src.p134),
 p134_label_hardcoded:/const inventedConcept = 'knuthgap'/.test(src.p134),
 p134_operator_not_compiled:/inventedConcept = 'knuthgap'[\s\S]*fn\$decodeNext[\s\S]*return probe \* 2654435761/.test(src.p134),
 p137b_honest:/ONTOLOGY_PROVIDED = true/.test(src.p137b)&&/genuineOntogenesis.*!ONTOLOGY_PROVIDED/.test(src.p137b),
 p138_problem_space_hardcoded:/const PROBLEM_SPACE = \[/.test(src.p138),
 p138_strategy_hardcoded:/switch \(p\.id\)/.test(src.p138),
 p138_value_baseline_hardcoded:/expectedValue = 0\.78/.test(src.p138)&&/const baselineValue = 0\.25/.test(src.p138),
 p138_real_dicel_compile:/\bcompile\s*\(/.test(src.p138),
 p140_honest_negative:/categoryEmerged = avgPairDist < 0\.3/.test(src.p140)&&/NO_CATEGORY_WITHOUT_FURNISHED_EQUIVALENCE/.test(src.p140),
};
const outputs={p137b_negative:/ontogenese_genuina \(sem ontologia fornecida\): false/.test(runs.p137b.stdout),p140_negative:/categoria de 2a ordem emergiu: false/.test(runs.p140.stdout),p138_skipped_attacks:(runs.p138.stdout.match(/sem API de fila/g)||[]).length};
// Independent adversarial checks
const p134MutantLabel='banana_gap';const p134NovelCheck=[...['add','sub'],p134MutantLabel].filter(x=>x===p134MutantLabel).length===1;
const p138Scores=[{id:'A',novelty:.9,difficulty:.85},{id:'B',novelty:1,difficulty:1}];const selector=x=>[...x].sort((a,b)=>b.novelty*b.difficulty-a.novelty*a.difficulty)[0].id;const p138SelectionChanges=selector(p138Scores)!=='A';
const p137bReport=fs.readFileSync(path.join(target,'audit','P137B_ONTOLOGY_GENERATION_REPORT.dicel'),'utf8');const p137bReportQuoteInvalid=/common_signature="\["_/.test(p137bReport);
const criteria={scripts_execute:Object.values(runs).every(x=>x.exit===0),hardcoded_candidate_free:!checks.p129_pre_authored,independent_oracle:!checks.p130_circular&&!checks.p134_circular_future,real_compiler_mutation:checks.p138_real_dicel_compile,semantic_operator_invention:!checks.p134_label_hardcoded&&!p134NovelCheck,open_problem_discovery:!checks.p138_problem_space_hardcoded&&!checks.p138_strategy_hardcoded,measured_external_utility:!checks.p138_value_baseline_hardcoded,honest_negative_controls:checks.p137b_honest&&checks.p140_honest_negative&&outputs.p137b_negative&&outputs.p140_negative,nontrivial_learning_cycle:false,real_patch_compile_test_compare:false,generated_reports_syntax_valid:!p137bReportQuoteInvalid};const pass=Object.values(criteria).filter(Boolean).length,total=Object.keys(criteria).length,status=pass>=7?'USEFUL_REAL_AUTO_IMPROVEMENT':pass>=4?'LIMITED_EXPERIMENTAL_UTILITY':'SIMULATION_WITH_USEFUL_NEGATIVE_CONTROLS';
const result={p137b_report_quote_invalid:p137bReportQuoteInvalid,target_head:'38fb7c524c8c281e6795dd734c469d0a80f36fa6',runs:Object.fromEntries(Object.entries(runs).map(([k,v])=>[k,{exit:v.exit,stdout_sha256:crypto.createHash('sha256').update(v.stdout).digest('hex')}])),checks,outputs,adversarial:{p134_arbitrary_hardcoded_label_passes_novel_check:p134NovelCheck,p138_selection_changes_when_designer_scores_change:p138SelectionChanges},criteria,criteria_pass:pass,criteria_total:total,final_status:status};fs.writeFileSync(path.join(out,'AUTO_IMPROVEMENT_UTILITY_AUDIT_V2.json'),JSON.stringify(result,null,2)+'\n');const L=[`@DICE-L:auto-improvement-utility-audit-v2:1.0.0;status=${status}`,`~AuditSummary{criteria_pass:${pass},criteria_total:${total},scripts_execute:${criteria.scripts_execute},real_compiler_mutation:${criteria.real_compiler_mutation},independent_oracle:${criteria.independent_oracle},honest_negative_controls:${criteria.honest_negative_controls},final_status:"${status}"}`,`~Finding{id:"AUTO2-001",category:"P134_circular_oracle",evidence:"predicted_and_actual_share_2654435761",status:"confirmed"}`,`~Finding{id:"AUTO2-002",category:"P134_hardcoded_novelty",evidence:"banana_gap_passes_same_unique_label_check",status:"confirmed"}`,`~Finding{id:"AUTO2-003",category:"P134_stub_representation",evidence:"knuthgap_label_not_present_in_compiled_operator_body",status:"confirmed"}`,`~Finding{id:"AUTO2-004",category:"P138_designer_roadmap",evidence:"hardcoded_problem_space_and_strategy_switch",status:"confirmed"}`,`~Finding{id:"AUTO2-005",category:"P138_subjective_metrics",evidence:"expected_value_cost_and_baseline_constants_pre_authored",status:"confirmed"}`,`~Finding{id:"AUTO2-006",category:"invalid_generated_dicel",evidence:"P137B_common_signature_contains_unescaped_nested_quotes",status:"confirmed"}`,`~Positive{id:"AUTO2-P01",category:"honest_negative_control",evidence:"P137b_ontology_supplied_true_and_genuine_ontogenesis_false"}`,`~Positive{id:"AUTO2-P02",category:"honest_negative_control",evidence:"P140_category_emerged_false"}`,`~Verdict{useful_for:"negative_controls_and_demo_benchmarks",not_proven_for:"real_autonomous_self_improvement",status:"${status}"}`];fs.writeFileSync(path.join(out,'AUTO_IMPROVEMENT_UTILITY_AUDIT_V2.dicel'),L.join('\n')+'\n');console.log(JSON.stringify({pass,total,status,checks,outputs},null,2));
