// ============================================================
// Generated by DICE-L v2 Compiler
// ============================================================

export function zlibVersion(): string {
  return "1.3.2.1-motley";
}

// ============================================================
// DICE-L Builtin Types
// ============================================================

export type Result<T, E> =
  | { ok: true; value: T }
  | { ok: false; error: E };

export type Option<T> = T | null;
